#!/bin/zsh

FOLDER="$1"
CREDENTIALS="$2"
FOLDERNAME="$3"

typeset -A albums

albums[AA]="Adrian Aliman"
albums[AAN]="Adrian Andrunachi"
albums[AS]="Alexandru Ştefan"
albums[AST]="Andreea State"
albums[AK]="Alfons Knobelspies"
albums[AB]="Andreea Baricz"
albums[AC]="Aristotel Căncescu"
albums[AM]="Ana Manea"
albums[AMO]="Ana Maria Oana"
albums[AMC]="Ana Maria Cazan"
albums[AG]="Anca Giugastru"
albums[BA]="Fam Balint"
albums[BE]="Badicu Eleonor"
albums[BB]="Bartha Biborka"
albums[BL]="Bartha Lorand"
albums[BEW]="Barabas Erwin"
albums[BME]="Bianca Mereţ"
albums[BJ]="Biblioteca Județeană"
albums[BM]="Biro Margit"
albums[BP]="Paul Balogh"
albums[CR]="Câlin Râpea"
albums[CG]="Camelia Gafitoi"
albums[CC]="Carmen Chiperea"
albums[CF]="Carmen Floroi"
albums[CM]="Muzeul Casa Mureşenilor"
albums[CFF]="Christian Ferencz-Flatz"
albums[CMM]="Ciprian Mircea Mănescu"
albums[CA]="Cimpoeşu Aurelia"
albums[CAV]="Constantin Avram"
albums[CD]="Cincu Dan"
albums[CID]="Clujescu Ioan Dan"
albums[CB]="Cristina Bogdan"
albums[CRG]="Cristi G"
albums[CS]="Cătălin Stroe"
albums[CCJ]="Cătălin Cojocaru"
albums[CSR]="Constantin Schuller"
albums[CO]="Costan Filimon"
albums[DI]="Dan Ionescu"
albums[DM]="Dan Mateescu"
albums[DP]="Dan Pavalache"
albums[DA]="Daneş Alexandru"
albums[DCO]="Daniel Copacea"
albums[DMO]="Daniela Moaşa"
albums[DC]="Fam. Dămoc"
albums[DG]="Deliu Gheorghe"
albums[DB]="Denes Bernad "
albums[DJ]="Doina Jighira"
albums[DRM]="Doina Marin"
albums[DCR]="Dan Cristescu"
albums[DS]="Dumitru Șchiopu"
albums[DR]="Dușa Romina"
albums[ER]="Edina Rosinecz"
albums[EN]="Emilia Nichifor"
albums[EB]="Elena Boureanu"
albums[EE]="Emanuel Erena"
albums[ELB]="Elena Barbu"
albums[EM]="Elena Micu"
albums[ES]="Ema Szabo"
albums[EV]="Edmund Vass"
albums[ET]="Erno Tamas"
albums[FC]="Felician Crişan"
albums[FT]="Florin Teodorescu"
albums[GC]="Gabriel Ciupa"
albums[GB]="Gabriela Butunoiu"
albums[GES]="Geramia Şerban"
albums[GG]="Georgia Gulea"
albums[GH]="Gruia Hilohi"
albums[GSC]="Gabriela Şchiopu"
albums[GS]="George S."
albums[GE]="Georgescu Ecaterina"
albums[GhM]="Ghiţescu Margareta "
albums[GM]="Giurgiu Maria "
albums[GO]="fam. Gotia"
albums[GU]="Fam. Gutunoi"
albums[HJ]="HANDRA JOZSEF"
albums[HD]="Herţa Daniela"
albums[HM]="Horia Morariu"
albums[HS]="Horia Stoica"
albums[ICA]="Ivan Cristina Andreea "
albums[IA]="Iulia Avram"
albums[JT]="Jakob Tunde"
albums[JN]="Juhasz Nicolae"
albums[KA]="Kadar Albert"
albums[KRR]="Kumria Rafail Rosu"
albums[LT]="La Vie Tănase"
albums[LCi]="Lavinia Ciobănescu"
albums[LU]="Leontin Ursache"
albums[LC]="Ligia Crăciun"
albums[LG]="Luana Georgescu"
albums[LJ]="Liliana Jighira"
albums[LI]="Luca Ioan"
albums[LCZ]="Lucian Cazac"
albums[LCR]="Lucian Crăciun"
albums[LD]="Lupu Daniel"
albums[MMM]="Macra Monica Margareta"
albums[MV]="Magda Vacariu"
albums[MMC]="Maria Cozma"
albums[MF]="Mariana Frâncu/ Maria David"
albums[MM]="Marin Gabriel-Mihai"
albums[MI]="Marina Iliescu"
albums[MIH]="Fam. Mihai"
albums[MRA]="Măriuca Radu"
albums[MN]="Meluş Negrescu"
albums[MAP]="Mihai Atanasie Petrescu "
albums[MB]="Mihai Bodea"
albums[MO]="Mihai Opriş"
albums[MP]="Milica Palade"
albums[MBR]="Mircea Brenciu"
albums[MD]="Mircea Dumbrăveanu"
albums[MDE]="Mariana Deliu"
albums[MDO]="Marius Dobrin"
albums[MCO]="Mirela Comanelea"
albums[MC]="Molnar Csaba"
albums[ML]="Molnar Lorant"
albums[MR]="Monica Radu"
albums[MOC]="Monica Coldea"
albums[MS]="Familia Moaşa"
albums[NI]="Fam. Neguţ Ionel"
albums[NIC]="Nicoleta"
albums[NG]="Nuţulescu George"
albums[ND]="Nossa Dana"
albums[OB]="Olimpia Bratucu"
albums[ODC]="Oana Davida Constantinescu"
albums[OD]="Olga Demeter"
albums[OG]="Ovidiu Gheorghian"
albums[OR]="Oana Rafoiu"
albums[PA]="Pana Anna"
albums[PB]="Petrache Butunoiu"
albums[PC]="Paul Chisăliţă"
albums[PD]="Pădineanu Dorina"
albums[PSR]="Muzeul Prina Şcoală Românească"
albums[RA]="Raluca"
albums[RG]="Raluca Garcea"
albums[RC]="Radu Colţea"
albums[RO]="Radu Oprea"
albums[RID]="Răzvan Ionuţ Dobrică"
albums[RB]="Robert Balazs"
albums[RBI]="Rodica Biriş"
albums[RMN]="Ruxandra Moaşa Nazare"
albums[RM]="Roxana Măcinic"
albums[SM]="Sanda Mureşan"
albums[SC]="Sebastian Constantin"
albums[SI]="Semenescu Iancu"
albums[SS]="Sipoș Ștefan"
albums[SO]="Sonia Câşlariu"
albums[SR]="Stelian Rotaru"
albums[SA]="Stoenescu Adriana"
albums[SB]="Steluţa Bulancea"
albums[SG]="Sever Gulea"
albums[SN]="Surdu Nicolae"
albums[ST]="Szabo Tiberiu"
albums[SV]="Suciu Vasile"
albums[SVA]="Suba Valeria"
albums[TA]="fam. Taloş"
albums[TFSB]="Tiberiu Florian Sonea Budu"
albums[TP]="Teaci Petru"
albums[TB]="Tiberiu Blaga"
albums[TZW]="Thiess Zoltan Walter"
albums[VA]="Vasile Aldea"
albums[VE]="Vasile Ene"
albums[VM]="Vasile Mihalache"
albums[VI]="Valentin Ivănescu"
albums[VS]="Valerica Ştefan"
albums[VV]="Viorica Viranyi"
albums[ZP]="Zena Popa"
albums[ZPM]="Monografie 'Judeţul Braşov sub arcul de lumină al epocii Nicolae Ceauşescu'"

find "$FOLDER" -type f \( -name "*.jpg" -or -name "*.png" -or -name "*.jpeg" -or -name "*.JPG" \) | while read file; do
    echo -en "\n\033[1;33mSplitting filename into tags \"$(basename "${file%.*}")\"\033[0m\n\n"

    # extract tags from file name
    MYFILE=$(basename "${file%.*}")
    TAGS=${MYFILE//_/,}

    # get album name from first tag
    array=("${(s/_/)MYFILE}")

    # ALBUM=${albums[VI]}
    ALBUM=${albums[${array[1]}]}
    echo $ALBUM
    
    # resize and compress jpgs
    gm mogrify -strip -resize 1600x1600\> "$(basename "${file}")"
    jpegoptim --m=80 -o "$(basename "${file}")"

    # send to AWS via api/add_photo
    echo -en "\n\033[1;33mUploading \"$(basename "${file}")\"\033[0m\n\n"
    curl -u "$CREDENTIALS" -include --form "tags=$TAGS" --form "file=@${file}" --form "folder=$FOLDERNAME" --form "album=$ALBUM" http://localhost:8080/api/add_photo
done
